<?php

namespace AppBundle\Repository;

/**
 * EngineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EngineRepository extends \Doctrine\ORM\EntityRepository
{
}
