<?php

namespace AppBundle\Repository;

/**
 * LabelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelsRepository extends \Doctrine\ORM\EntityRepository
{
}
