<?php

namespace AppBundle\Repository;

/**
 * MainChartDataMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainChartDataMSRepository extends \Doctrine\ORM\EntityRepository
{
}
