<?php

namespace AppBundle\Repository;

/**
 * MainChartDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainChartDataRepository extends \Doctrine\ORM\EntityRepository
{
}
