<?php

namespace AppBundle\Repository;

/**
 * main_chart_data_MSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class main_chart_data_MSRepository extends \Doctrine\ORM\EntityRepository
{
}
