<?php

namespace AppBundle\Repository;

/**
 * MainChartDataMSPowiatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainChartDataMSPowiatRepository extends \Doctrine\ORM\EntityRepository
{
}
