<?php

namespace AppBundle\Repository;

/**
 * RegistrationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationsRepository extends \Doctrine\ORM\EntityRepository
{
}
