<?php

namespace AppBundle\Repository;

/**
 * RegTotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegTotRepository extends \Doctrine\ORM\EntityRepository
{
}
