<?php

namespace AppBundle\Repository;

/**
 * TerytRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerytRepository extends \Doctrine\ORM\EntityRepository
{
}
