<?php

namespace AppBundle\Repository;

/**
 * TerytPowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerytPowRepository extends \Doctrine\ORM\EntityRepository
{
}
